const jCategory = [
  {
    index: 0,
    image: "../assets/google.png",
    title: "Web Developer",
    rate: "$900-1200/m",
    av: "Full Time",
    companyName: "Google",
    location: "USA",
    vacancy: "01",
    hours: "50h / week",
    position:"Web Developer",
    salary: "$900-1200/m",
    description: "We are seeking a talented and passionate Web Developer to design, develop, and maintain dynamic, user-friendly, and responsive websites. The ideal candidate should have a strong understanding of front-end and back-end technologies, attention to detail, and a drive to create seamless digital experiences.",
    workplace: "On site",
    education: "Bachelor degree in any Computer Science",
    experience : " 2 to 5 year(s)"
  },
  {
    index: 1,
    image: "../assets/facebook.jfif",
    title: "Digital Marketing",
    rate: "$900-1200/m",
    av: "Full Time",
    companyName: "Facebook",
    location: "USA",
    vacancy: "05",
    hours: "50h / week",
    position:"Digital Marketing",
    salary: "$900-1200/m",
    description: "We are looking for a creative and results-driven Digital Marketing Specialist to plan, execute, and optimize our online marketing campaigns across multiple digital channels. The ideal candidate will have a passion for digital technologies and stay up to date with the latest trends in online marketing, SEO, social media, and analytics.",
    workplace: "Remote",
    education: "Bachelor degree in Marketing, Business, or a related field.",
    experience : " 2 to 5 year(s) knowledge of graphic design and video editing tools."
  },
  {
    index: 2,
    image: "../assets/freelance.png",
    title: "Freelancer",
    rate: "$700-1200/m",
    av: "Freelancer",
    companyName: "Upwork",
    location: "USA",
    vacancy: "01",
    hours: "20h / week",
    position:"Freelancer",
    salary: "$700-1200/m",
    description: "We are looking for a skilled and reliable Freelancer to join our team on a project basis. The ideal candidate should be able to work independently, meet deadlines, and deliver high-quality results. You will be responsible for completing assigned tasks according to project requirements while maintaining clear communication throughout the process.",
    workplace: "Freelance / Remote",
    education: "Bachelor degree in any Computer Science",
    experience : "Proficiency in HTML/CSS, Photoshop, WordPress, Figma, etc."
  },
  {
    index: 3,
    image: "../assets/linkedin.png",
    title: "Business Associates",
    rate: "$1900-3200/m",
    av: "Part Time",
    companyName: "ZebTech Solutions",
    location: "USA",
    vacancy: "01",
    hours: "30h / week",
    position:"Business Analytics",
    salary: "$1900-3200/m",
    description: "We are looking for a Business Associate to support our team in managing business operations, improving performance, and driving strategic growth initiatives. The ideal candidate should be highly organized, detail-oriented, and able to work collaboratively with multiple departments to ensure smooth execution of business plans.",
    workplace: "On-site / Remote / Hybrid",
    education: "Bachelor’s degree in Business Administration, Management, Marketing, or a related field.",
    experience : " Experience in business development, operations, or project management."
  },
  {
    index: 4,
    image: "../assets/yahoo.png",
    title: "User Experience",
    rate: "$500-1000/m",
    av: "Part Time",
    companyName: "UXora",
    location: "USA",
    vacancy: "01",
    hours: "50h / week",
    position:"Web Developer",
    salary: "$900-1200/m",
    description: "We are looking for a creative and detail-oriented User Experience (UX) Designer to join our team. The ideal candidate will have a strong understanding of user-centered design principles and will be responsible for crafting engaging, intuitive, and accessible digital experiences across our web and mobile platforms.",
    workplace: "On site",
    education: "Degree in Design, HCI, Computer Science, or related field",
    experience : " 2 to 5 year(s) experience as a UX Designer, Product Designer, or similar role."
  },
]